services:
  server:
    image: portableclass/gpnitstart-server:latest
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_CONNECTION_STRING=mongodb+srv://new-user_1:IpTpPwsbzxwHUjd9@test.qdrzqq2.mongodb.net/gpnitstart?retryWrites=true&w=majority

  client:
    image: portableclass/gpnitstart-client:latest
    ports:
      - "8085:8085"
    environment:
      - VITE_API_URL=http://localhost:4000/api/
    depends_on:
      - server
